minimumReleaseAge: 2880 # 48 hrs
minimumReleaseAgeExclude:
  - '@next/*'
  - eslint-config-next
  - next
overrides:
  '@hono/node-server': 1.19.13
  'brace-expansion@1': ^1.1.18
  'brace-expansion@>=2': ^5.0.9
  postcss: 8.5.14
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - msw
  - nextjs-slides
